### PR TITLE
Fix endoint slash

### PR DESCRIPTION
**Pull request by Alkarex**
The URLs sent to the API contained a slash too much:

Example for FreshRSS:

```
"POST //api/greader.php/reader/api/0/edit-tag HTTP/1.1" 200 2 "-" "okhttp/4.12.0"

"GET //api/greader.php/reader/api/0/tag/list?output=json HTTP/1.1" 200 654 "-" "okhttp/4.12.0"
```

### CODE REVIEW

**Comment by Shinokuni** [comment]
Thanks for pointing this! However I think we should fix account url slash duplication earlier than in `Credentials`. As we get account url from `AccountCredentialsScreen`, url is always normalized before being inserted in database. That means we can just remove the end point first slash. Nextcloud News is also affected by this.

Could you replace your solution in `Credentials` by simply removing the first slash from FreshRSS API end point in [FreshRSSService](https://github.com/readrops/Readrops/blob/90875af4682e0dd09dc762af202a87127e774098/api/src/main/java/com/readrops/api/services/freshrss/FreshRSSService.kt#L95)?

**Comment by Alkarex** [comment]
Here you are

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/7039

**Comment by Alkarex** [comment]
The broken CI test does not seem to be due to my fix

**Comment by Shinokuni** [comment]
Oh okay so thank you for the fix but I must have explained it wrong 😅. I was talking about modifying directly the endpoint string in `FreshRSSService` instead of removing its first slash in `Credentials` as we shouldn't modify anything there.

We can ignore the CI as it seems to be a packaging error which appears sometimes and could be related to not enough memory for Gradle.

**Comment by Alkarex** [comment]
OK. Something like that?

**Pull request merged**
